# temp data in a city
Q1: calculate mean, max, min, and days of temp>30
Hint: use bool slicing or np.where

In [9]:
lst = [28, 30, 29, 31 ,32 ,30, 29]

import numpy as np
arr = np.array(lst)
print(np.mean(arr))
print(np.max(arr), np.min(arr))
print(np.size(arr[arr>30]))
print(np.where(arr>30, 1, 0))
print(np.cumsum(np.where(arr>30, 1, 0))[-1])
# additonal method
print(np.count_nonzero(arr>30))

29.857142857142858
32 28
2
[0 0 0 1 1 0 0]
2
2


# Studnets' grades
Q2: In a random sample of a classroom, calculate mean, var, median of the class, and convert to /150

In [11]:
score = [85, 90, 78, 92, 88]

arr = np.array(score)
print(np.mean(score))
print(np.median(score))
print(np.std(score))
print(np.var(score))

arr = np.array(score, dtype=int)
print(arr)
print(arr * 1.5)

86.6
88.0
4.882622246293481
23.84
[85 90 78 92 88]
[127.5 135.  117.  138.  132. ]


# Matrix calculations
Q3: A is a 2 by 2 matrix, B is also 2 by 2. Calculate product result mathmatically and with numpy way. conduct addition in both way.

In [13]:
A = [[1, 2], [3, 4]]
B = [[5, 6], [7, 8]]

arrA = np.array(A)
arrB = np.array(B)

# math
print(arrA + arrB)
print(arrA @ arrB)

# numpy
print(arrA + arrB)
print(arrA * arrB)

[[ 6  8]
 [10 12]]
[[19 22]
 [43 50]]
[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]


# Generate Random number series
Q4: Generate a 3 by 4 random int series, ranging [0, 10]
- calculate each row's min, and each column's max
- replace all odd numbers with -1

In [23]:
arr = np.random.randint(0, 11, (3,4))
print(arr)

# each colmun's max
for i in range(4):
    print(np.max(arr[:, i]))

# each row's min
for i in range(3):
    print(np.min(arr[i, :]))

# replacement
print(np.where(arr%2 == 1, -1, arr))

# Instructor's solution
np.random.seed(0)
arr = np.random.randint(0, 11, (3,4))
print(arr)
print(np.max(arr, axis=0))
print(np.min(arr, axis=1))
arr[arr%2==1] = -1
print(arr)

[[ 8  8 10  1]
 [ 6  7  7  8]
 [ 1  5  9  8]]
8
8
10
8
1
6
1
[[ 8  8 10 -1]
 [ 6 -1 -1  8]
 [-1 -1 -1  8]]
[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
[7 9 7 6]
[0 3 2]
[[-1  0 -1 -1]
 [-1 -1 -1 -1]
 [ 2  4 -1  6]]


# Reshape a data set
Q5: Construct a 1 to 12 number series, reshape to 3x4 matrix
- calculate each row's sum and each column's mean
- reshape back to one dimension

In [35]:
arr = np.linspace(1, 12, 12, dtype=int)
print(arr)
arr = np.reshape(arr, (3, 4))
print(arr)
# each row's sum
print(np.sum(arr, axis=1))
# each column's mean
print(np.mean(arr, axis=0))
# back to dim == 1
print(np.reshape(arr, (12)))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[10 26 42]
[5. 6. 7. 8.]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


# Gnerate a 3 x 3 random data, [0, 20)
Q6:
- find all elements > 10
- replace them with 0

In [43]:
arr = np.random.uniform(0, 20, (3, 3))
print(arr)
# > 10
print(arr[arr > 10])
# replace
print(np.where(arr>10, 0, arr))

# method two
arr[arr > 10] = 0
print(arr)

[[17.30205123 10.17937921 18.33445908]
 [18.4231522   1.66224985  5.55437123]
 [ 0.1871341  16.84684159 12.9434828 ]]
[17.30205123 10.17937921 18.33445908 18.4231522  16.84684159 12.9434828 ]
[[0.         0.         0.        ]
 [0.         1.66224985 5.55437123]
 [0.1871341  0.         0.        ]]
[[0.         0.         0.        ]
 [0.         1.66224985 5.55437123]
 [0.1871341  0.         0.        ]]


# Stats functions application
Q7: A company has a sale data sample of [120, 135, 110, 125, 130, 140]
- calculate sum, mean, var
- find the month which has the highest profit and the lowest

In [48]:
lst = [120, 135, 110, 125, 130, 140]

profit = np.array(lst)
print(np.sum(profit))
print(np.mean(profit))
print(np.var(profit))

# high/low month
print(np.argmax(profit) + 1)
print(np.argmin(profit) + 1)

760
126.66666666666667
97.22222222222223
6
3


# Joining number series
Q8: join horizontally/vertically

In [55]:
A = [1, 2, 3]
B = [4, 5, 6]

arrA = np.array(A)
arrB = np.array(B)

# horizontally
print(np.array(A + B))

# vertically
print(np.reshape(np.concatenate([arrA, arrB]), (2,3)))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


# Unique Value and sorting
Q9: Given a number series
- find unique value and sort
- calculate each unique value's times of appearance

In [57]:
lst = [2,1,2,3,1,4,3]

arr = np.array(lst)
print(np.unique(arr, return_counts = True))

(array([1, 2, 3, 4]), array([2, 2, 2, 1]))


# Missing Values
Q10: Given a number series
- calculate number of missing values
- replace them with 0

In [63]:
lst = [1, np.nan, 3, np.nan, 12]

arr = np.array(lst)
print(arr)

# sum
bool = np.isnan(arr)
print(bool)
process = np.where(bool, 1, 0)
print(process)
print(np.sum(process))

# replace
arr[np.isnan(arr)] = 0
print(arr)

[ 1. nan  3. nan 12.]
[False  True False  True False]
[0 1 0 1 0]
2
[ 1.  0.  3.  0. 12.]


# sales example
Q11: A store has a 5-day sales data and costs
- Calculate each day's profit
- calculate mean and standard de.. for the profit
- find the day with max profit

In [67]:
sales = [20, 25, 22, 30, 28]
costs = [15, 18, 16, 22, 20]

arr1 = np.array(sales)
arr2 = np.array(costs)

# profit
print(arr1 - arr2)

# mean, std
arr = arr1 - arr2
print(np.mean(arr), np.std(arr))

# highest
print(np.argmax(arr) + 1)

[5 7 6 8 8]
6.8 1.16619037896906
4


# Outlier!
Q11: Given a data
- Calculate Q1, Q2, Q3, IQR
- Conduct conclusion if Outlier exists
- Hint: +- 1.5IQR

In [82]:
lst = [-41, 10, 20, 30, 40, 50, 60, 70, 9999]

arr = np.array(lst)

# Q1 Q2 Q3 IQR
Q1 = np.percentile(arr, 25)
Q2 = np.median(arr)
Q3 = np.percentile(arr, 75)
IQR = Q3 - Q1
print(Q1, Q2, Q3, IQR)

# Fence
left = Q1 - 1.5 * IQR
right = Q3 + 1.5 * IQR
print(left, right)
arr1 = np.where((arr<left) | (arr>right), 1, 0)
print(arr1)
print(np.sum(arr1))

20.0 40.0 60.0 40.0
-40.0 120.0
[1 0 0 0 0 0 0 0 1]
2


# End of NUmpy :))))))))))))))))))