# ndarray
## 1, Properties of ndarray
### multiple dimensions(多维性)

In [1]:
import numpy as np

In [7]:
array = np.array(5) # int 5 -> np 0 dim arr
print(array)
print(array.ndim)
print(f"The dimension of array is {array.ndim}")

5
0
The dimension of array is 0


In [8]:
array = np.array([1, 2, 3]) # dim == 1
print(array.ndim)
print("The dimension of array is %s" % array.ndim)

1
The dimension of array is 1


Nested List -> np.array becomes dim 2

# Elements in np array have the same data type

In [9]:
array = np.array([1, "a"])
print(array) # Note the result elements should have the same dtype
print(array.ndim)
print("The dimension of array is %s" % array.ndim)

['1' 'a']
1
The dimension of array is 1


Example 2

In [10]:
array = np.array([1, 1.1])
print(array) # Note the result elements should have the same dtype
print(array.ndim)
print("The dimension of array is %s" % array.ndim)

[1.  1.1]
1
The dimension of array is 1


## 2, Utils

shape, ndim, size, dtype

In [11]:
# example
arr = np.array(100)
print(arr)
# shape
print("Shape is ", arr.shape)
# ndim dimensions
print("Dimension: ", arr.ndim)
# size similar to len
print("size == ", arr.size)
# dtype
print("Data type is : ", arr.dtype)

100
Shape is  ()
Dimension:  0
size ==  1
Data type is :  int64


In [12]:
# another example
arr = np.array([[1 , 2, 3], [4, 5, 6]])
print(arr)
# shape
print("Shape is ", arr.shape)
# ndim dimensions
print("Dimension: ", arr.ndim)
# size similar to len
print("size == ", arr.size)
# dtype
print("Data type is : ", arr.dtype)

[[1 2 3]
 [4 5 6]]
Shape is  (2, 3)
Dimension:  2
size ==  6
Data type is :  int64


T, itemsize, nbytes, flags

In [14]:
# example
arr = np.array([[1 , 2, 3], [4, 5, 6]])
print(arr)
arr_T = arr.T
print(arr_T)
# shape
print("Shape is ", arr.shape)
print("T_Shape is ", arr_T.shape)
# ndim dimensions
print("Dimension: ", arr.ndim)
print("T_Shape is ", arr_T.ndim)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
Shape is  (2, 3)
T_Shape is  (3, 2)
Dimension:  2
T_Shape is  2


Other utils(not common used but for optimizations)

In [18]:
# example
arr = np.array([[1 , 2, 3], [4, 5, 6]])

# Other utils
print(arr.itemsize) # each int is 8 bytes
print(arr.nbytes)   # 6 elements 6 x 8 == 48
print(arr.flags)    # saved continously in memory?

8
48
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [19]:
# T shaped
arr = arr_T
print(arr.itemsize)
print(arr.nbytes)
print(arr.flags)

8
48
  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

