#

# Method of creation - ndarray
## 1, Basic method

In [1]:
# Basic method
import numpy as np
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


In [3]:
lst = [1, 2, 3] # py list
arr = np.array(lst)
print(arr)

[1 2 3]


In [4]:
# Common used peremetre - dtype
lst = [1, 2, 3, 4, 5, 6]
arr = np.array(lst, dtype = np.float64)
print(arr)

[1. 2. 3. 4. 5. 6.]


In [5]:
# copy
arr_ = np.copy(arr)
print(arr_)

[1. 2. 3. 4. 5. 6.]


In [10]:
# Note this copy method is a deep copy when its dtype is numerical values
arr_a = np.array([[1, 2, 3]])
print(arr_a)
arr_b = np.copy(arr_a)
arr_a[0][0] = 99
print(arr_a)
print(arr_b)

[[1 2 3]]
[[99  2  3]]
[[1 2 3]]


In [17]:
# However when its object type, copy is shallow in some version

## 2, Pre-set the shape of array

In [20]:
# all 0s, 1s, constants, uninitialized
# 1: all 0s
arr = np.zeros((2, 3)) # 2x3 zero matrix
print(arr)
print(arr.dtype)
arr = np.zeros((2, 3), dtype = int) # 2x3 zero matrix(int)
print(arr)
print(arr.dtype)

[[0. 0. 0.]
 [0. 0. 0.]]
float64
[[0 0 0]
 [0 0 0]]
int64


In [21]:
# 1: all 0s example dim == 1
arr = np.zeros((15,))
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [22]:
# 2: all 1s
arr = np.ones((4, 6))
print(arr)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [53]:
# 3: constants
arr = np.full((3, 4), "Data Science")
print(arr)

[['Data Science' 'Data Science' 'Data Science' 'Data Science']
 ['Data Science' 'Data Science' 'Data Science' 'Data Science']
 ['Data Science' 'Data Science' 'Data Science' 'Data Science']]


In [52]:
# 4 : uninitialized
arr = np.empty((3, 9))
print(arr)

[[6.23042070e-307 3.56043053e-307 1.60219306e-306 2.44763557e-307
  1.69119330e-306 1.78019625e-306 1.11260280e-306 3.56043054e-307
  7.56595733e-307]
 [1.00131040e-307 8.34424766e-308 6.23038675e-307 1.02361342e-306
  6.23059726e-307 1.06811422e-306 8.45558624e-307 9.34601642e-307
  1.60219035e-306]
 [2.22522597e-306 6.23060744e-307 8.90111708e-307 1.11260144e-306
  6.23059726e-307 1.33511562e-306 6.89805151e-307 2.56765117e-312
  2.56765117e-312]]


In [57]:
# Optional Util
arr = np.ones((4, 6), dtype = int)
arr_1 = np.zeros_like(arr) # copy the shape,dtype but fill with 0s
print(arr_1)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
