# Indexing and Slicing in numpy

## 1 Basic indexing & slicing

In [21]:
import numpy as np
# single dimension example
arr = np.random.randint(1, 100, 21)
print(arr)
print(arr[0])
print(arr[-1])
print(arr[0:4])
# the same as py

[14 24 50 86  4 71 95 66 22  8 88 40 80 54 39 66 39 67 92 15 20]
14
20
[14 24 50 86]


## Bool way

In [25]:
arr = np.linspace(0, 100, 6)
print(arr)
print(arr[arr>=60]) # students who pass the course

[  0.  20.  40.  60.  80. 100.]
[ 60.  80. 100.]


In [63]:
# example two
# 500 students - normal dist
arr = np.random.randn(1, 352) * 21 + 52
# z = x - u / sigma x = z sigma + u
# print(arr[0])
arr = arr[(arr>=0) & (arr<=100)] # and
# or is |
# print(arr)
arr_pass = arr[arr>=60]
print(f"{arr_pass.size} students passed the course this year, which is {arr_pass.size/arr.size} of the course")

114 students passed the course this year, which is 0.32386363636363635 of the course


## Two dimensions

In [67]:
arr = np.random.randint(1, 100, (4, 8))
print(arr)
print(arr[0][-1]) # first row last column
print(arr[0,-1])

[[59 39 40 38 54 49 10 34]
 [30 41 55 68 48 90 87  4]
 [13 10 29 48 90 57 10 95]
 [45 27 19 28 92  9 44 31]]
34
34


In [69]:
arr = np.random.randint(1, 100, (4, 8))
print(arr)
print(arr[1, :]) # 2nd row
print(arr[:, 1]) # 2nd column

[[70 85 99 72 63 91  5 65]
 [82  9 91 81 37 20 24 15]
 [99 94 79 44 63 45 22 55]
 [57 96 29 42 47 92 76 34]]
[82  9 91 81 37 20 24 15]
[85  9 94 96]


In [71]:
arr = np.random.randint(1, 100, (4, 8))
print(arr)
print(arr[arr>50]) # res diim == 1
# example get d3rd column's > 50 data
print(arr[:, 2][arr[:, 2] > 50])

[[36 30 25 27 31 25 24 40]
 [43 51 53 26 71 13 19 29]
 [79 54 44 17 45 64 53 56]
 [38 28 81 29 12 40 76 61]]
[51 53 71 79 54 64 53 56 81 76 61]
[53 81]


End