# Ndarray -calculations

In [6]:
import numpy as np
# + - * /
arr1 = np.linspace(1, 3, 3, dtype = int)
arr2 = np.linspace(4, 6, 3, dtype = int)
print(arr1, arr2)
print(arr1 + arr2)
print(arr2 - arr1)
print(arr1 * arr2)
print(arr2 / arr1)

[1 2 3] [4 5 6]
[5 7 9]
[3 3 3]
[ 4 10 18]
[4.  2.5 2. ]


In [7]:
# Recall: python
lst1 = [1, 2, 3]
lst2 = [4, 5, 6]
print(lst1 + lst2)

[1, 2, 3, 4, 5, 6]


In [18]:
a = np.eye(3, 3)
b = np.array([[1, 2, 3], [4, 5, 5], [7, 8 ,9]])
c = np.zeros((3, 3))
print(c)
print(a + c)
print(a - c)
print(a * b)
print(c + 3)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 5. 0.]
 [0. 0. 9.]]
[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]


In [19]:
# broadcast
# for single dimension if number is the same or onr of them is 1
# boradcast = true
# example a: 1 * 3 b: 3 * 1
# for first "1" in a and "3" in b as there's a one
# the same with 3 in a and 1 in b so broadcast = true
a = np.array([1, 2, 3])
b = np.array([[4],[5],[6]])
'''a
123
123
123

b
4 4 4
5 5 5
6 6 6
'''
print(a+b)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


## Matrix calculation

In [21]:
a = np.eye(3, 3)
b = np.zeros((3, 3))
c = np.array([[1, 2, 3], [4, 5, 5], [7, 8 ,9]])
print(a @ c)
print(b @ c)

[[1. 2. 3.]
 [4. 5. 5.]
 [7. 8. 9.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
