# Functions in ndarray

## Math functions

In [2]:
import numpy as np
arr = np.array([1, 4, 9], dtype=int)
# sqrt - > float
print(np.sqrt(arr))
# exponential e^x
arr = np.array([0, 1], dtype=int)
print(np.exp(arr))
# Ln(x)
print(np.log(2.71)) # 2.71 -> e
# sin cos
print(np.sin(np.pi/6))
print(np.cos(np.pi/3))
# abs
arr = np.array([1,-2,-3])
print(np.abs(arr))
# a^b
print(np.power(arr, 3))
# rounding
arr = np.array([1.1,-2.4,-.5, 3.5])
print(np.round(arr))
# ceiling floor
print(np.ceil(arr))
print(np.floor(arr))

[1. 2. 3.]
[1.         2.71828183]
0.9969486348916096
0.49999999999999994
0.5000000000000001
[1 2 3]
[  1  -8 -27]
[ 1. -2. -0.  4.]
[ 2. -2. -0.  4.]
[ 1. -3. -1.  3.]


In [18]:
# check for NaN (missing value)
np.isnan([1, 2, np.nan, 9])

array([False, False,  True, False])

## Stats functions

In [3]:
# sum, mean, median, sd, sd^2, max, min, percentile, ....
arr = np.random.randint(1, 20, 8)
print(arr)

[13  8 16  4  2 15 12 13]


In [4]:
# sum
print(np.sum(arr))

83


In [5]:
# mean
print(np.mean(arr))

10.375


In [6]:
# median
print(np.median(arr))

12.5


In [12]:
# sd^2
print(np.var(arr))
# sd
print(np.std(arr))

23.234375
4.8202048711647105


In [9]:
# max
print(np.max(arr))

16


In [10]:
# min
print(np.min(arr))

2


In [13]:
# percentile
print(np.percentile(arr,25)) # 0.25 percentile (Q1)

7.0


In [14]:
# ACCUMULATING sum/product
arr = np.array([1,2,3])
print(np.sum(arr))
print(np.cumsum(arr))

6
[1 3 6]
