# Functions in ndarray

## Math functions

In [2]:
from email.policy import default

import numpy as np
arr = np.array([1, 4, 9], dtype=int)
# sqrt - > float
print(np.sqrt(arr))
# exponential e^x
arr = np.array([0, 1], dtype=int)
print(np.exp(arr))
# Ln(x)
print(np.log(2.71)) # 2.71 -> e
# sin cos
print(np.sin(np.pi/6))
print(np.cos(np.pi/3))
# abs
arr = np.array([1,-2,-3])
print(np.abs(arr))
# a^b
print(np.power(arr, 3))
# rounding
arr = np.array([1.1,-2.4,-.5, 3.5])
print(np.round(arr))
# ceiling floor
print(np.ceil(arr))
print(np.floor(arr))

[1. 2. 3.]
[1.         2.71828183]
0.9969486348916096
0.49999999999999994
0.5000000000000001
[1 2 3]
[  1  -8 -27]
[ 1. -2. -0.  4.]
[ 2. -2. -0.  4.]
[ 1. -3. -1.  3.]


In [18]:
# check for NaN (missing value)
np.isnan([1, 2, np.nan, 9])

array([False, False,  True, False])

## Stats functions

In [3]:
# sum, mean, median, sd, sd^2, max, min, percentile, ....
arr = np.random.randint(1, 20, 8)
print(arr)

[13  8 16  4  2 15 12 13]


In [4]:
# sum
print(np.sum(arr))

83


In [5]:
# mean
print(np.mean(arr))

10.375


In [6]:
# median
print(np.median(arr))

12.5


In [12]:
# sd^2
print(np.var(arr))
# sd
print(np.std(arr))

23.234375
4.8202048711647105


In [9]:
# max
print(np.max(arr))

16


In [10]:
# min
print(np.min(arr))

2


In [13]:
# percentile
print(np.percentile(arr,25)) # 0.25 percentile (Q1)

7.0


In [14]:
# ACCUMULATING sum/product
arr = np.array([1,2,3])
print(np.sum(arr))
print(np.cumsum(arr))

6
[1 3 6]


## Comparing functions

In [16]:
# > < =
print(np.greater([2,3,4,4,5], 3))
print(np.less([2,3,4,4,5], 3))
print(np.equal([2,3,4,4,5], 3))

[False False  True  True  True]
[ True False False False False]
[False  True False False False]


In [19]:
print(np.equal([2, 3, 4], [2, 4, 4]))

[ True False  True]


In [21]:
# # or and not
print(np.logical_and([1, 0], [1, 1]))
# replace and with or, not

[ True False]


In [23]:
# any, all
print(np.any([0, 0, 0, 1]))
print(np.all([1, 1, 1, 0]))

True
False


In [29]:
# customized conditions
arr = np.array([1, 2, 3, 4 ,5])
print(np.where(arr<3,1,0))
# classify example
score = np.random.randint(0, 100, 20)
print(score)
print(np.where(score<50, "Fail",
               np.where(score<85, "Pass", "4.0")))
# ALTERNATIVE WAY
print(np.select([score < 50, (score>=50) & (score<85), score>=85],
                ['fail', 'pass', '4.0'],
                default = 'unknwon'))

[1 1 0 0 0]
[39 17 59 37 18 89 18 60 73 55 99 84 83 24 51 61 48  5 61 15]
['Fail' 'Fail' 'Pass' 'Fail' 'Fail' '4.0' 'Fail' 'Pass' 'Pass' 'Pass'
 '4.0' 'Pass' 'Pass' 'Fail' 'Pass' 'Pass' 'Fail' 'Fail' 'Pass' 'Fail']
['fail' 'fail' 'pass' 'fail' 'fail' '4.0' 'fail' 'pass' 'pass' 'pass'
 '4.0' 'pass' 'pass' 'fail' 'pass' 'pass' 'fail' 'fail' 'pass' 'fail']
