# Functions in ndarray

## Math functions

In [17]:
import numpy as np
arr = np.array([1, 4, 9], dtype=int)
# sqrt - > float
print(np.sqrt(arr))
# exponential e^x
arr = np.array([0, 1], dtype=int)
print(np.exp(arr))
# Ln(x)
print(np.log(2.71)) # 2.71 -> e
# sin cos
print(np.sin(np.pi/6))
print(np.cos(np.pi/3))
# abs
arr = np.array([1,-2,-3])
print(np.abs(arr))
# a^b
print(np.power(arr, 3))
# rounding
arr = np.array([1.1,-2.4,-.5, 3.5])
print(np.round(arr))
# ceiling floor
print(np.ceil(arr))
print(np.floor(arr))

[1. 2. 3.]
[1.         2.71828183]
0.9969486348916096
0.49999999999999994
0.5000000000000001
[1 2 3]
[  1  -8 -27]
[ 1. -2. -0.  4.]
[ 2. -2. -0.  4.]
[ 1. -3. -1.  3.]


In [18]:
# check for NaN (missing value)
np.isnan([1, 2, np.nan, 9])

array([False, False,  True, False])