# Series Properties

In [12]:
import pandas as pd

s = pd.Series([1, 2, 3, 4, 5], name = 'test')
print(s)

print(s.index)
print(s.values)
print(s.ndim)
print(s.shape)
print(s.size)
print(s.dtype)
print(s.name)

0    1
1    2
2    3
3    4
4    5
Name: test, dtype: int64
RangeIndex(start=0, stop=5, step=1)
[1 2 3 4 5]
1
(5,)
5
int64
test


In [11]:
s1 = pd.Series({'a' : 1, 'b' : 2, 'c' : 3}, name = 'ex2')
print(s1)

print(s1.index)
print(s1.values)

# loc iloc at iat

# support slicing ....
print(s1.loc['a'])
print(s1.iloc[0])

# faster for single element indexing
print(s1.at["a"])
print(s1.iat[1])

a    1
b    2
c    3
Name: ex2, dtype: int64
Index(['a', 'b', 'c'], dtype='object')
[1 2 3]
1
1
1
2


# Access Data

In [17]:

print(s1['a']) # 'a' is okay but 1 is not okay , because 1 might be lable name or index
print(s1[s1<3])
# similar as R
print(s1.head(2))
print(s1.tail(2))

1
a    1
b    2
Name: ex2, dtype: int64
a    1
b    2
Name: ex2, dtype: int64
b    2
c    3
Name: ex2, dtype: int64


# Utils

In [22]:
import numpy as np
s = pd.Series([10, 2, np.nan, None, 4, 5, 6], index = ["A", 'B','C', 'D', 'E', 'F', 'G'], name = 'Data')
print(s)

A    10.0
B     2.0
C     NaN
D     NaN
E     4.0
F     5.0
G     6.0
Name: Data, dtype: float64


In [24]:
print(s.head(3))
print(s.tail()) # default : 5 lines

A    10.0
B     2.0
C     NaN
Name: Data, dtype: float64
C    NaN
D    NaN
E    4.0
F    5.0
G    6.0
Name: Data, dtype: float64


In [25]:
s.describe() # count does not count None or np.nan

count     5.000000
mean      5.400000
std       2.966479
min       2.000000
25%       4.000000
50%       5.000000
75%       6.000000
max      10.000000
Name: Data, dtype: float64

In [41]:
print(s.count()) # no na none
print(s.size) # elements

5
7


In [42]:
# keys
print(s.keys())
print(s.index)

Index(['A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='object')
Index(['A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='object')


In [43]:
# missing value
print(s.isna())

A    False
B    False
C     True
D     True
E    False
F    False
G    False
Name: Data, dtype: bool


In [45]:
# 'in' or not
s.isin([4]) # must be list - like

A    False
B    False
C    False
D    False
E     True
F    False
G    False
Name: Data, dtype: bool

In [57]:
 # stats functions
print(s.mean(), s.std(), s.var(), s.max(), s.min(), s.sum(), sep='\n')
print("\n sep \n")
print(s.median())
print(s.quantile(.25))
print(s.mode()) # every value show one time so all are mode

5.4
2.9664793948382653
8.8
10.0
2.0
27.0

 sep 

5.0
4.0
0     2.0
1     4.0
2     5.0
3     6.0
4    10.0
Name: Data, dtype: float64


In [63]:
s = pd.Series([1, 2, 3, 4, 5, 5, 5, 5, np.nan, None, np.nan])
print(s.values)
print(s.value_counts())

[ 1.  2.  3.  4.  5.  5.  5.  5. nan nan nan]
5.0    4
1.0    1
2.0    1
3.0    1
4.0    1
Name: count, dtype: int64


In [67]:
# drop duplicates keep the first shown value and index
print(s.drop_duplicates()) # -> series
print(s.nunique())
s.unique() # -> list

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
8    NaN
dtype: float64
5


array([ 1.,  2.,  3.,  4.,  5., nan])

In [68]:
# sorting
s.sort_index()

0     1.0
1     2.0
2     3.0
3     4.0
4     5.0
5     5.0
6     5.0
7     5.0
8     NaN
9     NaN
10    NaN
dtype: float64

In [69]:
s.sort_values()

0     1.0
1     2.0
2     3.0
3     4.0
4     5.0
5     5.0
6     5.0
7     5.0
8     NaN
9     NaN
10    NaN
dtype: float64